# Scaling-Up matrix multiplication

In [1]:
import dask.array as da
from dask.distributed import Client
import time
from scale_cluster import init_cluster
from scale_cluster import kill_cluster

In [3]:
client = Client('170.210.103.20:8786')
print(client)

<Client: scheduler='tcp://170.210.103.20:8786' processes=0 cores=0>


In [9]:
init_cluster('170.210.103.20', str(1), str(24))
time.sleep(5)
client = Client('170.210.103.20:8786')
print(client)

<Client: scheduler='tcp://170.210.103.20:8786' processes=13 cores=312>


In [7]:
kill_cluster('170.210.103.20')
time.sleep(10)

In [2]:
# Settings Init Cluster
max_workers = 3  # It depends settings cluster
max_cores_by_workers = 24

# Settings Init Matrix
n_rows_x = 1000
n_col_x = 2000
n_rows_y = 2000
n_col_y = 1000

# Init vars matrix
x_1 = da.ones((n_rows_x,n_col_x), dtype=int)
y_1 = da.ones((n_rows_y,n_col_y), dtype=int)
sequential_time = 4
speed_ups = []
#mult = da.matmul(x_1,y_1)
#res = mult.compute()
#res

### Get time sequential

In [3]:
init_cluster('170.210.103.20', str(1), str(1))
time.sleep(5)
client = Client('170.210.103.20:8786')
print(client)
# Execute task
t = time.time()
#mult = da.matmul(x_1,y_1)
#res = mult.compute()

sequential_time = time.time()-t
print('Result:')
print(res)
print('With nodes:1 '+'cores_by_workers: '+str(1)+ '\tTime: '+ str(sequential_time))    
print('----------------------------------------------------------')
kill_cluster('170.210.103.20')
time.sleep(10)

<Client: scheduler='tcp://170.210.103.20:8786' processes=1 cores=1>
Result:
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:1 cores_by_workers: 1	Time: 17.728991985321045
----------------------------------------------------------


### Get Speed_Ups

In [4]:
for j in range(1,max_cores_by_workers+1):    
    init_cluster('170.210.103.20', str(3), str(j))
    time.sleep(5)
    client = Client('170.210.103.20:8786')
    print(client)
    # Execute task
    t = time.time()
    mult = da.matmul(x_1,y_1)
    res = mult.compute()
    t1 = time.time()-t
    speed_ups.append(t1/sequential_time)
    print(res)
    print('With nodes:3 '+'cores_by_workers: '+str(j)+ '\tTime: '+ str(t1))    
    print('----------------------------------------------------------')
    kill_cluster('170.210.103.20')
    time.sleep(15)

<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=3>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 1	Time: 18.20842456817627
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=6>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 2	Time: 17.7902352809906
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=9>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000

tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=39>>
Traceback (most recent call last):
  File "/home/mario/dask/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/client.py", line 930, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat-client'})
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError


<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=42>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 14	Time: 17.99370312690735
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=45>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 15	Time: 17.778382539749146
----------------------------------------------------------


tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=45>>
Traceback (most recent call last):
  File "/home/mario/dask/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/client.py", line 930, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat-client'})
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError


<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=48>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 16	Time: 17.71151828765869
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=51>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 17	Time: 17.7340407371521
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=54>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000

tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=57>>
Traceback (most recent call last):
  File "/home/mario/dask/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/client.py", line 930, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat-client'})
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError


<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=60>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 20	Time: 17.854057788848877
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=63>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 21	Time: 17.87324857711792
----------------------------------------------------------


tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=63>>
Traceback (most recent call last):
  File "/home/mario/dask/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/client.py", line 930, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat-client'})
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError


<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=66>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 22	Time: 18.042117595672607
----------------------------------------------------------
<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=69>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 23	Time: 17.75746488571167
----------------------------------------------------------


tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=69>>
Traceback (most recent call last):
  File "/home/mario/dask/lib/python3.6/site-packages/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/client.py", line 930, in _heartbeat
    self.scheduler_comm.send({'op': 'heartbeat-client'})
  File "/home/mario/dask/lib/python3.6/site-packages/distributed/batched.py", line 117, in send
    raise CommClosedError
distributed.comm.core.CommClosedError


<Client: scheduler='tcp://170.210.103.20:8786' processes=3 cores=72>
[[2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 ...
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]
 [2000 2000 2000 ... 2000 2000 2000]]
With nodes:3 cores_by_workers: 24	Time: 17.761680364608765
----------------------------------------------------------


### Plot Speed-Ups

In [5]:
import matplotlib.pyplot as plt
cores = 3
x = []
for s in speed_ups:
    x.append(cores)
    cores += 3
plt.plot(x, speed_ups)
plt.ylabel('Speed-Up')
plt.xlabel('Cores')
plt.show()

<Figure size 640x480 with 1 Axes>

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46150 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46148 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46166 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46184 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46224 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46232 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp://170.210.103.13:46300 remote=tcp://170.210.103.20:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP local=tcp:/